### ISSUE TITLE
Local block is not published in case of content approval

### ISSUE THREAD

**Issue by gregwiechec** [episerver/EPiServer.Labs.BlockEnhancements#1]
**Steps to reproduce**:
1. Create Block1 in Page1's For This Page folder
2. Enable Approval Sequence settings on Page1 -> Block1 inherits the settings
3. Send Page1 for review
4. Approve Page1
5. Click Publish > "Publish with local content items" menu on Page1
6. Click Publish button with Block1 selected

**Actual**: Page1 is published but Block1 is not.
**Expected**: Block1 somehow must follow the Approval Sequence as for Page1 before publish

**Comment by barteksekula** [comment]
We disabled publish for items that have an active approval sequence.
