### ISSUE TITLE
Feature request: Enable on-page editing of block properties

### ISSUE THREAD

**Issue by PaulGruffyddAmaze** [episerver/EPiServer.Labs.BlockEnhancements#13]
Although this package adds the functionality to edit the content of block without leaving the content containing the block (i.e. fields appear as a form within a modal when the block is clicked), it would be a great enhancement if the properties of a block within a content area could be edited directly via on-page editing in the same way as properties directly on the content being edited.

**Comment by JasonRodman** [comment]
When I first heard of this new feature, I though on-page editing is what they were referring to. It would be a huge advancement if they added this since this would be much more useful than a popup properties editor.

**Comment by barteksekula** [comment]
I completely agree, however that's a huge feature. We have to analyze this carefully.

**Comment by barteksekula** [comment]
Block enahancements are going to be obsoleted. Most of its functionality is being moved to CMS UI package. A new compatibility release will be released soon, compatible with 12.18.0
On page editing of local blocks will be included eventually in the core CMS UI
