### ISSUE TITLE
Publish Changes Only Shown When Reloaded

### ISSUE THREAD

**Issue by ScottReed** [episerver/EPiServer.Labs.BlockEnhancements#17]
If you use the Inline Edit on a piece of content that is published and save it the menu item for Publish Changes does not appear unless you refresh the page.

Repro Steps

- Have published content in a content area
- Inline edit and change the content
- Menu item does not appear

**Comment by ChazKlein** [comment]
@ScottReed Keep running into the exact same bug.

**Comment by barteksekula** [comment]
This one will be fixed in the next minor, together with #4

**Comment by barteksekula** [comment]
Fixed in https://nuget.episerver.com/package/?id=EPiServer.Labs.BlockEnhancements&v=0.3.1
