### ISSUE TITLE
Browse Existing Content Not Working

### ISSUE THREAD

**Issue by ScottReed** [episerver/EPiServer.Labs.BlockEnhancements#18]
The new browse existing content is not working for me. I have a site running

- CMS 11.12.0
- Commerce 13.6.0

When I try to load dialog I just get a loading screen and the request I can see in Devtools get's a 404

![image](https://user-images.githubusercontent.com/1773620/63868525-93a3f880-c9ae-11e9-9671-4a1c1a47e08d.png)

It does seem to be working when I'm in the Commerce View but not in CMS

**Comment by barteksekula** [comment]
@ScottReed would it be possible for you to give it a shot on a clean Alloy site created from VS? if that will work then maybe we can try to identify the differences between two solutions.
That would help a lot to nail down the problem, thanks.

**Comment by seriema** [comment]
We appreciate your help @ScottReed. Episerver provides limited support to Labs, mainly on it's functionality with CMS UI, and this seems to be a bug related to using it with another add-on. That said, due to the open source nature of Labs we hope you or someone is willing to contribute a fix.

**Comment by ScottReed** [comment]
Problem was with web.config configuration for max querystring length. Out of the box with none set I am getting errors but adding 

`<security>
    <requestFiltering>
      <requestLimits maxQueryString="32768"/>
    </requestFiltering>
  </security>`

In to the web.config area under `<location path="EPiServer"` fixed the issue

**Comment by barteksekula** [comment]
@ScottReed could you please check the url that was failing?
you would see it just after clicking Browse existing content, something like this:
`http://yourhost/EPiServer/cms/Stores/contentstructure/?referenceId=1&query=getchildren&typeIdentifiers=episerver.core.icontentdata&sort()&dojo.preventCache=1568036401714`

**Comment by ScottReed** [comment]
The URL was causing the issue when I take that fix out again when clicking the "Browse Exisitng Content" was as you expected above. Here's the full URL

https://dev.site.redweb.network/EPiServer/cms/Stores/contentstructure/103?typeIdentifiers=redweb.episerver.models.blocks.advice.adviceheroblock&typeIdentifiers=episerver.core.contentfolder&typeIdentifiers=redweb.episerver.models.blocks.advice.advicesearchblock&typeIdentifiers=redweb.episerver.models.blocks.structure.breadcrumbblock&typeIdentifiers=redweb.episerver.models.blocks.course.courseinfoheroblock&typeIdentifiers=redweb.episerver.models.blocks.search.coursesearchblock&typeIdentifiers=redweb.episerver.models.blocks.course.courseselectionblock&typeIdentifiers=redweb.episerver.models.blocks.common.ctablock&typeIdentifiers=redweb.episerver.models.blocks.events.eventdetailblock&typeIdentifiers=redweb.episerver.models.blocks.common.heroblock&typeIdentifiers=redweb.episerver.models.blocks.common.herocarouselblock&typeIdentifiers=redweb.episerver.models.blocks.advice.largeadvicesearchblock&typeIdentifiers=redweb.episerver.models.blocks.shop.largecategorycalloutblock&typeIdentifiers=redweb.episerver.models.blocks.search.largecoursesearchblock&typeIdentifiers=redweb.episerver.models.blocks.volunteeringopportunities.largevolunteersearchblock&typeIdentifiers=redweb.episerver.models.blocks.structure.primaryheadingblock&typeIdentifiers=redweb.episerver.models.blocks.search.quicksearchblock&typeIdentifiers=redweb.episerver.models.blocks.volunteeringopportunities.opportunityheroblock&typeIdentifiers=redweb.episerver.models.blocks.volunteeringopportunities.opportunitysearchblock&typeIdentifiers=redweb.episerver.models.blocks.common.podlinksrowblock&typeIdentifiers=redweb.episerver.models.blocks.shop.productcategoryheroblock&typeIdentifiers=redweb.episerver.models.blocks.structure.rowblock&typeIdentifiers=redweb.episerver.models.blocks.structure.rowblockwithsidebar&typeIdentifiers=redweb.episerver.models.blocks.structure.rowblockwithtitle&typeIdentifiers=redweb.episerver.models.blocks.search.sitesearchblock&typeIdentifiers=redweb.episerver.models.blocks.shop.shopheroblock&typeIdentifiers=redweb.episerver.models.blocks.search.shopsearchblock&typeIdentifiers=redweb.episerver.models.blocks.volunteeringopportunities.vacancysearchblock&typeIdentifiers=redweb.episerver.models.blocks.common.sitemapblock&allLanguages=false&dojo.preventCache=1568714888483

**Comment by barteksekula** [comment]
@ScottReed could you please share the AllowedTypes configuration on that ContentArea property? I assume there's some base class there right? CMS UI has quite complex logic behind calculating the explicit types of content that can be added to a ContentArea based on provided interfaces/base classes which in some environments (with a lot of content types) may result in urls that long.
In that case I'm afraid I won't be able to do anything from here.
`maxQueryString` would be the correct solution.

**Comment by barteksekula** [comment]
This is a bug in CMS, will be reported there. Will post back the version it was fixed in here.

**Comment by ssanch** [comment]
Hey @barteksekula do you happen to have more info about this? I am currently experiencing this issue and I'd like to see what the bug is and what I can do about it.

The `maxQueryString` works in the sense that items load but things take up to 1 minute and a half which is a lot of time. I'd like to improve those times.
