### ISSUE TITLE
Content Area Icons Not Showing In Commerce Editor

### ISSUE THREAD

**Issue by ScottReed** [episerver/EPiServer.Labs.BlockEnhancements#19]
Although the icons area showing in the CMS view within Episerver Commerce the Content Area is not showing any of the custom icons

CMS 11.12.0
Commerce 13.6.0

![image](https://user-images.githubusercontent.com/1773620/63869015-64da5200-c9af-11e9-9fb4-c49f11c25a9e.png)

**Comment by seriema** [comment]
We appreciate your help @ScottReed. Episerver provides limited support to Labs, mainly on it's functionality with CMS UI, and this seems to be a bug related to using it with another add-on. That said, due to the open source nature of Labs we hope you or someone is willing to contribute a fix.

**Comment by ScottReed** [comment]
Thanks, if I can I'll see if I can see anything that would indicate why this is or at least some errors as I'm not up on my Dojo,

**Comment by ScottReed** [comment]
I don't have the time to fix but I've seen the error I think. The icons are actually appearing but not showing and it looks like CSS.

On the CMS one that's working the icon DOM elements are rendering as such

`<span data-dojo-attach-point="iconNodeStatus" class="dijitTreeIcon epi-extraIcon epi-statusIndicatorIcon epi-statusIndicator2" role="presentation" title="Not visible until published">&nbsp;</span>`

However on the Commerce view they are appearing with

`<span data-dojo-attach-point="iconNodeStatus" class="dijitTreeIcon epi-extraIcon epi-statusIndicatorIcon epi-statusIndicator4" role="presentation" title="">&nbsp;</span>

From playing with it it's `due to the fact epi-statusIndicator2 has **background-position: 0 -16px;** and epi-statusIndicator4 showing in the Commerce view does not.

**Comment by barteksekula** [comment]
@ScottReed the class is epi-statusIndicatorX where X is the content.Status
2 is unpublished (pen icon visible)
4 is published (no extra icon visible)

Are you sure your content area items are not published?
I've just checked and I can see the icons:
![image](https://user-images.githubusercontent.com/1321664/64535621-e7e89a00-d317-11e9-9c36-7fe7d545c68d.png)

**Comment by ScottReed** [comment]
Sorry I was away last week. I've updated to the latest version and it seems fine to me, I may have been being an iditiot and using the inline edit which had a bug until the new version where the icon doesn't appear but looks fine to me now. Thanks for the feedback
