### ISSUE TITLE
Icon Showing View Instead of Edit When First Loading Page

### ISSUE THREAD

**Issue by ScottReed** [episerver/EPiServer.Labs.BlockEnhancements#20]
When we first load any page the first item on in the ContenArea is showing View and a magnifying glass instead of the usual Edit. If you then open the block popup menu on any of the other blocks in the ContentArea and then go back to the first the menu then correctly reshows Edit with the pencil icon. I've unintalled the package and confirmed it's from this module.

Below is a comparison of page loading on first time and selection the first item in the content area compared to after opening any menu on any of the other blocks and reopening the first item.

![icon-issues](https://user-images.githubusercontent.com/1773620/64329171-b5146e00-cfc6-11e9-8525-171359cc97ba.png)

**Comment by barteksekula** [comment]
Fixed in https://nuget.episerver.com/package/?id=EPiServer.Labs.BlockEnhancements&v=0.3.1
