### ISSUE TITLE
Smart Publish and Inline Block Edit doesn't work if ContentArea is CultureSpecific=false

### ISSUE THREAD

**Issue by hallatore** [episerver/EPiServer.Labs.BlockEnhancements#21]
Repro:
- Page A exists in `en` (master) and `no`.
- Page A has a ContentArea which is set to CultureSpecific = false.
- The blocks in this area all exist in both `en` and `no`.

1. Inline page edit is grayed out.
2. When editing the blocks they show up with correct block status. But when opening Smart Publish they are not listed.

**Comment by barteksekula** [comment]
@hallatore I fixed p1 but I have a question about p2. I think I reproduced that problem but just need a confirmation that I'm actually fixing the right thing ; )
Smart publish seems to work fine for me in the master lang, however I do see the problem in the following scenario:

1. Page A exists in en (master) and no.
2. Page A has a ContentArea which is set to CultureSpecific = false.
3. Block B exists in both en and no languages
4. Block B is added to ContentArea in the master en language
5. Page A is published
6. User switches to no and still sees BlockB in the content area (grayed out)
7. User inline edits the block (will work after [a87dad2](https://github.com/episerver/EPiServer.Labs.BlockEnhancements/commit/a87dad270a45ae3995b721a9b042883076532dee)) or edits in the standard way and go back
8. User clicks Smart Publish and does not see BlockB (no)

**Comment by hallatore** [comment]
@barteksekula That is the scenario I'm talking about. :)

**Comment by hallatore** [comment]
@barteksekula Would love to test out 0.3.2 as soon as these two are fixed. This package is a huge improvement for our editors.

**Comment by barteksekula** [comment]
Released in https://nuget.episerver.com/package/?id=EPiServer.Labs.BlockEnhancements&v=0.3.2
