### ISSUE TITLE
long block type names no tooltip

### ISSUE THREAD

**Issue by mhwlng** [episerver/EPiServer.Labs.BlockEnhancements#25]
See :
![image](https://user-images.githubusercontent.com/1388886/68381217-87c47780-0151-11ea-9f6a-af623812276a.png)

These block are called :
`Featured Products Block`
and
`Featured Products Block Header`
A tooltip to show the full block type name would be useful

**Comment by barteksekula** [comment]
@mhwlng The issue has been fixed in https://nuget.episerver.com/package/?id=EPiServer.Labs.BlockEnhancements&v=0.5.1
