### ISSUE TITLE
Imagevault property not showing image in inline edit

### ISSUE THREAD

**Issue by LucGosso** [episerver/EPiServer.Labs.BlockEnhancements#26]
Hey yo! great work! 

Was about to implement it to a customer but inline edit does not work properly with the Imagevault Property.

Image is not loaded from db. - no works!
you can insert new image and save - works!

I do not know if this is a matter for ImageVault? or for this project. Whats your opinion? 

![ScreenHunter 168](https://user-images.githubusercontent.com/9716195/68657697-82da3c00-0534-11ea-9f66-acd27f166d23.png)
![ScreenHunter 166](https://user-images.githubusercontent.com/9716195/68657700-8372d280-0534-11ea-824a-09827374c680.png)
![ScreenHunter 167](https://user-images.githubusercontent.com/9716195/68657698-82da3c00-0534-11ea-8c4d-3bfe4f8f3c32.png)

ImageVault.EPiServer.UI | 11.6.155.0
EPiServer.Labs.BlockEnhancements | 0.5.0
EPiServer.UI  | 11.21.7.0

Probably some init context missing?

**Comment by barteksekula** [comment]
any errors in the console?

**Comment by LucGosso** [comment]
Nothing in console. No errors. 

Ive reported it to Imagevault (Meriworks) Issue #11594

I guess we let them test it and see if they need assistans.

**Comment by barteksekula** [comment]
I debugged imagevault sources and I think I found the problem. I contacted Meriworks, hopefully they will be able to fix it.

**Comment by barteksekula** [comment]
Fixed in https://www.nuget.org/packages/ImageVault.EPiServer.UI/11.7.71
