### ISSUE TITLE
Show a loader when opening smart publish

### ISSUE THREAD

**Issue by hallatore** [episerver/EPiServer.Labs.BlockEnhancements#29]
Get calls like `http://localhost/EPiServer/episerver-labs-block-enhancements/Stores/episerverlabsblockenhancements/1745_536244` can take quite a time to load. (9 seconds on my machine 😅)

The dialog displays "There is nothing to publish" until this call is done loading. Which is quite confusing for the editors.

**Comment by barteksekula** [comment]
Could you please let me know a bit more about your solution?
How many items do you have on the list? Do you have approvals/projects enabled?

**Comment by barteksekula** [comment]
Any feedback @hallatore? We need some data to check what is wrong.

**Comment by hallatore** [comment]
When you click "Smart publish" the following dialog pops up.

![image](https://user-images.githubusercontent.com/365605/70356292-559f5600-1874-11ea-9482-b16bc76d4c70.png)

The issue is that the text `There is nothing to be published` is displayed before the rest call is finished. So when the connection is a bit slow then it's easy to misunderstand.

I suggest changing this text to "Checking for changes ..." or something similar. And only changing it when the rest call is done loading. (Only way to tell is that the table headers are gone once it's done loading)

PS: The rest call is usually quite fast. But if it's slow for some reason, then there is no way to know that for the editor.

**Comment by barteksekula** [comment]
@hallatore Sure, I get the idea why we need the preloader. Just wanted to find out what was the scenario when it took 9 seconds on your machine.
