### ISSUE TITLE
Shows View menu instead of Edit menu on Content Area item

### ISSUE THREAD

**Issue by gregwiechec** [episerver/EPiServer.Labs.BlockEnhancements#3]
**Steps to reproduce**:
1. Edit a content item having an editable Content Area property
2. Open context menu of any content item in Content Area property

**Expected**: Shows Edit menu item.
**Actual**: Shows View menu item instead of Edit.
**Observed**: It just happens on the first clicked content item in a Content Area property.
**Notes**: Nu such issue in case of not installing EPiServer.Labs.BlockEnhancements.

**Comment by barteksekula** [comment]
Fixed in https://nuget.episerver.com/package/?id=EPiServer.Labs.BlockEnhancements&v=0.3.1
