### ISSUE TITLE
Unable to create new form container in-line because of 'Connect to Datasource'

### ISSUE THREAD

**Issue by dlwniels** [episerver/EPiServer.Labs.BlockEnhancements#31]
When I try to create a new form container in-line, I can't since it makes the 'Connect to Datasource'-field required. 

![image](https://user-images.githubusercontent.com/47145826/70035096-8d777680-15b2-11ea-8386-8a0c6d08890d.png)

I also don't even have any datasources locally, so I can't fill in any value.

![image](https://user-images.githubusercontent.com/47145826/70035157-a4b66400-15b2-11ea-9492-f8c7750c2ed5.png)

I can create this block the old way, so this issue is related to the in-line editing.

**Comment by barteksekula** [comment]
Could you please share the model with that "Connect to datasource" property?

**Comment by dlwniels** [comment]
Hi,

This field is defined in an the Episerver.Forms package itself.

Here is my wrapper for the default Episerver forms formcontainer:
https://gist.github.com/dlwniels/f042f29695d5c218f9d9144c778d5c5c

I decompiled FormContainerBlock, but can't seem to find that field in there. I suppose it is injected or so, but it is default Episerver forms functionality.

**Comment by barteksekula** [comment]
Can you please move the issue to https://github.com/advanced-cms/forms ?

**Comment by dlwniels** [comment]
Hi, I didn't have this package. I installed it but the problem remains. I'll log the issue over there.
