### ISSUE TITLE
Floating TinyMCE dropdowns

### ISSUE THREAD

**Issue by dlwniels** [episerver/EPiServer.Labs.BlockEnhancements#33]
When collapsing a dropdown in the TinyMCE editor, when creating a new page/block in-line, the dropdown is out of place.

![image](https://user-images.githubusercontent.com/47145826/70125151-99c50780-1676-11ea-98e6-668407c48cac.png)

![image](https://user-images.githubusercontent.com/47145826/70125166-a21d4280-1676-11ea-9d40-4b97ad874017.png)

**Comment by rbare1** [comment]
@dlwniels What versions of CMS UI and Episerver TinyMCE are you using?

**Comment by barteksekula** [comment]
Reproduced on TinyMCE 2.9.0 without block enhancements package.

**Comment by rbare1** [comment]
https://world.episerver.com/support/bug-list/bug/CMS-15062
