### ISSUE TITLE
Episerver edit interface does not work when using swedish as edit language

### ISSUE THREAD

**Issue by hesta96** [episerver/EPiServer.Labs.BlockEnhancements#34]
When a user is using Swedish as the editor interface language there is js errors that makes the editor interface unusable.

![image](https://user-images.githubusercontent.com/6217258/70506106-daff6080-1b29-11ea-9c8d-57f0d40c31e1.png)

`epi.js:2 Uncaught TypeError: Cannot use 'in' operator to search for 'inlinepublish' in 
          
    at _8 (epi.js:2)
    at _c (epi.js:2)
    at epi.js:2
    at _c8 (dojo.js:15)
    at _36 (dojo.js:15)
    at dojo.js:15
    at _37 (dojo.js:15)
    at _7c (dojo.js:15)
    at _f0 (dojo.js:15)
    at HTMLScriptElement._10a (dojo.js:15)
_8 @ epi.js:2
_c @ epi.js:2
(anonymous) @ epi.js:2
_c8 @ dojo.js:15
_36 @ dojo.js:15
(anonymous) @ dojo.js:15
_37 @ dojo.js:15
_7c @ dojo.js:15
_f0 @ dojo.js:15
_10a @ dojo.js:15
load (async)
_101 @ dojo.js:15
req.injectUrl @ dojo.js:15
_32 @ dojo.js:15
_9 @ dojo.js:15
(anonymous) @ dojo.js:15
_37 @ dojo.js:15
_77 @ dojo.js:15
_16 @ dojo.js:15
_87 @ dojo.js:15
load @ epi.js:2
_e7 @ dojo.js:15
_32 @ dojo.js:15
_9 @ dojo.js:15
(anonymous) @ dojo.js:15
_37 @ dojo.js:15
_77 @ dojo.js:15
(anonymous) @ dojo.js:15
_9 @ dojo.js:15
_7b @ dojo.js:15
_f0 @ dojo.js:15
_10a @ dojo.js:15
load (async)
_101 @ dojo.js:15
req.injectUrl @ dojo.js:15
_32 @ dojo.js:15
_9 @ dojo.js:15
(anonymous) @ dojo.js:15
_37 @ dojo.js:15
_77 @ dojo.js:15
(anonymous) @ dojo.js:15
_9 @ dojo.js:15
_7b @ dojo.js:15
_f0 @ dojo.js:15
_10a @ dojo.js:15
load (async)
_101 @ dojo.js:15
req.injectUrl @ dojo.js:15
_32 @ dojo.js:15
_9 @ dojo.js:15
(anonymous) @ dojo.js:15
_37 @ dojo.js:15
_77 @ dojo.js:15
(anonymous) @ dojo.js:15
_9 @ dojo.js:15
_7b @ dojo.js:15
_f0 @ dojo.js:15
_10a @ dojo.js:15
load (async)
_101 @ dojo.js:15
req.injectUrl @ dojo.js:15
_32 @ dojo.js:15
_9 @ dojo.js:15
(anonymous) @ dojo.js:15
_37 @ dojo.js:15
_77 @ dojo.js:15
(anonymous) @ dojo.js:15
_9 @ dojo.js:15
_7b @ dojo.js:15
_f0 @ dojo.js:15
_10a @ dojo.js:15
load (async)
_101 @ dojo.js:15
req.injectUrl @ dojo.js:15
_32 @ dojo.js:15
_9 @ dojo.js:15
(anonymous) @ dojo.js:15
_37 @ dojo.js:15
_77 @ dojo.js:15
_16 @ dojo.js:15
req @ dojo.js:15
_runModuleInitializer @ epi.js:2
(anonymous) @ epi.js:2
_2f2 @ dojo.js:15
then._2ff.then @ dojo.js:15
when @ dojo.js:15
(anonymous) @ epi.js:2
_2f2 @ dojo.js:15
then._2ff.then @ dojo.js:15
when @ dojo.js:15
_startModule @ epi.js:2
(anonymous) @ epi.js:2
forEach @ dojo.js:15
(anonymous) @ epi.js:2
_2f2 @ dojo.js:15
_2ec @ dojo.js:15
resolve @ dojo.js:15
_2f2 @ dojo.js:15
_2ec @ dojo.js:15
resolve @ dojo.js:15
(anonymous) @ epi.js:2
(anonymous) @ dojo.js:15
_2f2 @ dojo.js:15
_2ec @ dojo.js:15
resolve @ dojo.js:15
_2f8 @ dojo.js:15
_2f2 @ dojo.js:15
_2ec @ dojo.js:15
resolve @ dojo.js:15
_2f8 @ dojo.js:15
_2f2 @ dojo.js:15
_2ec @ dojo.js:15
resolve @ dojo.js:15
_2f8 @ dojo.js:15
_2f2 @ dojo.js:15
_2ec @ dojo.js:15
resolve @ dojo.js:15
_2f8 @ dojo.js:15
_2f2 @ dojo.js:15
_2ec @ dojo.js:15
resolve @ dojo.js:15
_2f2 @ dojo.js:15
_2ec @ dojo.js:15
resolve @ dojo.js:15
(anonymous) @ widgets.js:2
(anonymous) @ dojo.js:15
_2f2 @ dojo.js:15
_2ec @ dojo.js:15
resolve @ dojo.js:15
_2f2 @ dojo.js:15
_2ec @ dojo.js:15
resolve @ dojo.js:15
(anonymous) @ widgets.js:2
_2f2 @ dojo.js:15
_2ec @ dojo.js:15
resolve @ dojo.js:15
_2f8 @ dojo.js:15
(anonymous) @ dojo.js:15
_2f2 @ dojo.js:15
then._2ff.then @ dojo.js:15
_2f2 @ dojo.js:15
_2ec @ dojo.js:15
resolve @ dojo.js:15
_2f8 @ dojo.js:15
(anonymous) @ dojo.js:15
_2cd @ dojo.js:15
_2cb @ dojo.js:15
resolve.callback @ dojo.js:15
_2cd @ dojo.js:15
_2cb @ dojo.js:15
resolve.callback @ dojo.js:15
_2cd @ dojo.js:15
_2cb @ dojo.js:15
resolve.callback @ dojo.js:15
_2cd @ dojo.js:15
_2cb @ dojo.js:15
resolve.callback @ dojo.js:15
_2cd @ dojo.js:15
_2cb @ dojo.js:15
resolve.callback @ dojo.js:15
(anonymous) @ dojo.js:15
_2f2 @ dojo.js:15
_2ec @ dojo.js:15
resolve @ dojo.js:15
_2f8 @ dojo.js:15
_2f2 @ dojo.js:15
_2ec @ dojo.js:15
resolve @ dojo.js:15
_2f8 @ dojo.js:15
_2f2 @ dojo.js:15
_2ec @ dojo.js:15
resolve @ dojo.js:15
_2f8 @ dojo.js:15
_2f2 @ dojo.js:15
_2ec @ dojo.js:15
resolve @ dojo.js:15
_4f2 @ dojo.js:15
_4fe @ dojo.js:15
load (async)
_4f8 @ dojo.js:15
xhr @ dojo.js:15
dojo.xhr @ dojo.js:15
_sendRequest @ widgets.js:2
(anonymous) @ widgets.js:2
(anonymous) @ dojo.js:15
_2f2 @ dojo.js:15
then._2ff.then @ dojo.js:15
xhr @ widgets.js:2
xhr @ widgets.js:2
_xhr @ widgets.js:2
xhr @ widgets.js:2
xhrGet @ widgets.js:2
get @ widgets.js:2
_c15 @ widgets.js:2
_c1a.<computed> @ widgets.js:2
(anonymous) @ widgets.js:2
when @ dojo.js:15
get @ widgets.js:2
get @ widgets.js:2
getContentLanguage @ widgets.js:2
initialize @ widgets.js:2
(anonymous) @ epi.js:2
(anonymous) @ dojo.js:15
_c8 @ dojo.js:15
_36 @ dojo.js:15
(anonymous) @ dojo.js:15
_37 @ dojo.js:15
_7c @ dojo.js:15
_f0 @ dojo.js:15
_10a @ dojo.js:15
load (async)
_101 @ dojo.js:15
req.injectUrl @ dojo.js:15
_32 @ dojo.js:15
_9 @ dojo.js:15
(anonymous) @ dojo.js:15
_37 @ dojo.js:15
_77 @ dojo.js:15
_16 @ dojo.js:15
_87 @ dojo.js:15
load @ epi.js:2
_e7 @ dojo.js:15
_32 @ dojo.js:15
_9 @ dojo.js:15
(anonymous) @ dojo.js:15
_37 @ dojo.js:15
_77 @ dojo.js:15
(anonymous) @ dojo.js:15
_9 @ dojo.js:15
_7b @ dojo.js:15
_f0 @ dojo.js:15
_32 @ dojo.js:15
_9 @ dojo.js:15
(anonymous) @ dojo.js:15
_37 @ dojo.js:15
_77 @ dojo.js:15
(anonymous) @ dojo.js:15
_9 @ dojo.js:15
_7b @ dojo.js:15
_f0 @ dojo.js:15
_32 @ dojo.js:15
_9 @ dojo.js:15
(anonymous) @ dojo.js:15
_37 @ dojo.js:15
_77 @ dojo.js:15
_16 @ dojo.js:15
req @ dojo.js:15
_runModuleInitializer @ epi.js:2
(anonymous) @ epi.js:2
_2f2 @ dojo.js:15
then._2ff.then @ dojo.js:15
when @ dojo.js:15
(anonymous) @ epi.js:2
_2f2 @ dojo.js:15
_2ec @ dojo.js:15
resolve @ dojo.js:15
(anonymous) @ epi.js:2
_2f2 @ dojo.js:15
_2ec @ dojo.js:15
resolve @ dojo.js:15
_2f2 @ dojo.js:15
_2ec @ dojo.js:15
resolve @ dojo.js:15
(anonymous) @ epi.js:2
(anonymous) @ dojo.js:15
_2f2 @ dojo.js:15
_2ec @ dojo.js:15
resolve @ dojo.js:15
_2f8 @ dojo.js:15
_2f2 @ dojo.js:15
_2ec @ dojo.js:15
resolve @ dojo.js:15
_2f2 @ dojo.js:15
_2ec @ dojo.js:15
resolve @ dojo.js:15
(anonymous) @ widgets.js:2
(anonymous) @ dojo.js:15
_2f2 @ dojo.js:15
_2ec @ dojo.js:15
resolve @ dojo.js:15
_2f2 @ dojo.js:15
_2ec @ dojo.js:15
resolve @ dojo.js:15
(anonymous) @ widgets.js:2
_2f2 @ dojo.js:15
_2ec @ dojo.js:15
resolve @ dojo.js:15
_2f8 @ dojo.js:15
(anonymous) @ dojo.js:15
_2f2 @ dojo.js:15
then._2ff.then @ dojo.js:15
_2f2 @ dojo.js:15
_2ec @ dojo.js:15
resolve @ dojo.js:15
_2f8 @ dojo.js:15
(anonymous) @ dojo.js:15
_2cd @ dojo.js:15
_2cb @ dojo.js:15
resolve.callback @ dojo.js:15
_2cd @ dojo.js:15
_2cb @ dojo.js:15
resolve.callback @ dojo.js:15
_2cd @ dojo.js:15
_2cb @ dojo.js:15
resolve.callback @ dojo.js:15
_2cd @ dojo.js:15
_2cb @ dojo.js:15
resolve.callback @ dojo.js:15
_2cd @ dojo.js:15
_2cb @ dojo.js:15
resolve.callback @ dojo.js:15
(anonymous) @ dojo.js:15
_2f2 @ dojo.js:15
_2ec @ dojo.js:15
resolve @ dojo.js:15
_2f8 @ dojo.js:15
_2f2 @ dojo.js:15
_2ec @ dojo.js:15
resolve @ dojo.js:15
_2f8 @ dojo.js:15
_2f2 @ dojo.js:15
_2ec @ dojo.js:15
resolve @ dojo.js:15
_2f8 @ dojo.js:15
_2f2 @ dojo.js:15
_2ec @ dojo.js:15
resolve @ dojo.js:15
_4f2 @ dojo.js:15
_4fe @ dojo.js:15
load (async)
_4f8 @ dojo.js:15
xhr @ dojo.js:15
dojo.xhr @ dojo.js:15
_sendRequest @ widgets.js:2
(anonymous) @ widgets.js:2
(anonymous) @ dojo.js:15
_2f2 @ dojo.js:15
then._2ff.then @ dojo.js:15
xhr @ widgets.js:2
xhr @ widgets.js:2
_xhr @ widgets.js:2
xhr @ widgets.js:2
xhrGet @ widgets.js:2
query @ widgets.js:2
query @ widgets.js:2
_e30.query @ widgets.js:2
_c15 @ widgets.js:2
_c1a.<computed> @ widgets.js:2
initialize @ widgets.js:2
(anonymous) @ widgets.js:2
(anonymous) @ dojo.js:15
when @ dojo.js:15
initialize @ widgets.js:2
(anonymous) @ epi.js:2
(anonymous) @ dojo.js:15
_c8 @ dojo.js:15
_36 @ dojo.js:15
(anonymous) @ dojo.js:15
_37 @ dojo.js:15
_7c @ dojo.js:15
_f0 @ dojo.js:15
_10a @ dojo.js:15
load (async)
_101 @ dojo.js:15
req.injectUrl @ dojo.js:15
_32 @ dojo.js:15
_9 @ dojo.js:15
(anonymous) @ dojo.js:15
_37 @ dojo.js:15
_77 @ dojo.js:15
(anonymous) @ dojo.js:15
_9 @ dojo.js:15
_7b @ dojo.js:15
_f0 @ dojo.js:15
_32 @ dojo.js:15
_9 @ dojo.js:15
(anonymous) @ dojo.js:15
_37 @ dojo.js:15
_77 @ dojo.js:15
(anonymous) @ dojo.js:15
_9 @ dojo.js:15
_7b @ dojo.js:15
_f0 @ dojo.js:15
_32 @ dojo.js:15
_9 @ dojo.js:15
(anonymous) @ dojo.js:15
_37 @ dojo.js:15
_77 @ dojo.js:15
(anonymous) @ dojo.js:15
_9 @ dojo.js:15
_7b @ dojo.js:15
_f0 @ dojo.js:15
_32 @ dojo.js:15
_9 @ dojo.js:15
(anonymous) @ dojo.js:15
_37 @ dojo.js:15
_77 @ dojo.js:15
_16 @ dojo.js:15
req @ dojo.js:15
_runModuleInitializer @ epi.js:2
(anonymous) @ epi.js:2
_2f2 @ dojo.js:15
then._2ff.then @ dojo.js:15
when @ dojo.js:15
(anonymous) @ epi.js:2
_2f2 @ dojo.js:15
then._2ff.then @ dojo.js:15
when @ dojo.js:15
_startModule @ epi.js:2
(anonymous) @ epi.js:2
map @ dojo.js:15
_startRequiredModules @ epi.js:2
_startModule @ epi.js:2
startModules @ epi.js:2
initializeApplication @ epi.js:2
(anonymous) @ (index):51
_c8 @ dojo.js:15
_36 @ dojo.js:15
(anonymous) @ dojo.js:15
_37 @ dojo.js:15
_7c @ dojo.js:15
_f0 @ dojo.js:15
_10a @ dojo.js:15
load (async)
_101 @ dojo.js:15
req.injectUrl @ dojo.js:15
_32 @ dojo.js:15
_9 @ dojo.js:15
(anonymous) @ dojo.js:15
_37 @ dojo.js:15
_77 @ dojo.js:15
_16 @ dojo.js:15
_87 @ dojo.js:15
load @ epi.js:2
_e7 @ dojo.js:15
(anonymous) @ dojo.js:15
_9 @ dojo.js:15
_d1 @ dojo.js:15
_35 @ dojo.js:15
_36 @ dojo.js:15
(anonymous) @ dojo.js:15
_37 @ dojo.js:15
_7c @ dojo.js:15
_16 @ dojo.js:15
req @ dojo.js:15
(anonymous) @ DojoDashboardCompatibility.js:1
(anonymous) @ DojoDashboardCompatibility.js:1
Show 316 more frames
epi.js:2 Uncaught TypeError: Cannot use 'in' operator to search for 'inlinereadytopublish' in 
          
    at _8 (epi.js:2)
    at _c (epi.js:2)
    at epi.js:2
    at _c8 (dojo.js:15)
    at _36 (dojo.js:15)
    at dojo.js:15
    at _37 (dojo.js:15)
    at _7c (dojo.js:15)
    at _f0 (dojo.js:15)
    at HTMLScriptElement._10a (dojo.js:15)`

**Comment by barteksekula** [comment]
I don't understand what was the exact problem here but this commit fixed the issue.
https://github.com/episerver/EPiServer.Labs.BlockEnhancements/commit/d3e952a9e0df0a49c0fe97c6aff160109a1fff0c?diff=split

0.6.1 will soon be available on the nuget feed. sorry for trouble.
