### ISSUE TITLE
Inline editing cuts off submit and cancel buttons on smaller displays

### ISSUE THREAD

**Issue by JDoyleAdageDev** [episerver/EPiServer.Labs.BlockEnhancements#39]
I noticed an issue that is only visible on smaller displays where the block title as well as the submit and cancel buttons are being cut off. The following screenshot was taken on a 13 inch MacBook. 
![Inline editing bug](https://user-images.githubusercontent.com/56134055/71114614-c2302400-2195-11ea-83ea-95db29d230cd.jpg)

I believe this is very similar to https://github.com/episerver/EPiServer.Labs.BlockEnhancements/issues/23 but was perhaps not accounting for very small screens. The screenshot was taken on version 0.6.2, but was also reported on version 0.5.2. 

Thanks!

**Comment by barteksekula** [comment]
@JDoyleAdageDev what's your screen res?

**Comment by barteksekula** [comment]
@JDoyleAdageDev any info? 13inch macbook has 2560 x 1600 res. But looking at your screenshot it seems the resolution is much lower.

**Comment by JDoyleAdageDev** [comment]
Hi @barteksekula,
I was mistaken. This screenshot was taken on an 11 inch MacBook with a 1366 x 768 resolution. Sorry about that! 
Also once the browser size reduced to 66% everything is visible again. Hopefully that helps.
