### ISSUE TITLE
New changes are not saved when inline published

### ISSUE THREAD

**Issue by gregwiechec** [episerver/EPiServer.Labs.BlockEnhancements#4]
**Steps to reproduce**:

Edit a page that contains a block in content area property
Inline edit the block then save
Inline edit the block again. At this time, "Publish Changes" button is visible to user
Change something and click on "Publish Changes" button
Expected result:
The block is published with the new changes

**Actual result**:
The block is published without the new changes.

**Comment by barteksekula** [comment]
Fixed in https://nuget.episerver.com/package/?id=EPiServer.Labs.BlockEnhancements&v=0.3.1
