### ISSUE TITLE
Issue saving a form in the popup editor.

### ISSUE THREAD

**Issue by PatrikFomin** [episerver/EPiServer.Labs.BlockEnhancements#40]
I can't get the save button to work when I try to add or update a form using the popup editor. Nothing happens when I click save except that it sets the tab to MA System Database (foundation).

![image](https://user-images.githubusercontent.com/18208521/71190043-1e717180-2284-11ea-95ac-8de4fb84bec1.png)

**Comment by barteksekula** [comment]
Please move the issue to https://github.com/advanced-cms/forms
EPiServer.Labs.BlockEnhancements does not officially support Forms.

**Comment by PatrikFomin** [comment]
Anyone with access that can move it? Otherwise I can close and re-create it.

**Comment by seriema** [comment]
@PatrikFomin I don't have access to advanced-cms to move it there. It might be faster for you to do it, or wait until @barteksekula or @gregwiechec see this.

**Comment by barteksekula** [comment]
@PatrikFomin just create an issue in the other repo and close this one. thanks
