### ISSUE TITLE
AppInsights Telemetry

### ISSUE THREAD

**Issue by robinjac** [episerver/EPiServer.Labs.BlockEnhancements#41]
Hello everyone!

As promised we would like to keep our development of telemetry gathering via AppInsights transparent to the public so everyone knows what's going on and can contribute with feedback. 

You can see the current state of our development [here]( https://github.com/episerver/EPiServer.Labs.BlockEnhancements/tree/feature/CMS-14776-base-implementation-running-in)

**Comment by barteksekula** [comment]
Released in https://github.com/episerver/EPiServer.Labs.BlockEnhancements/pull/44
Nuget available here https://nuget.episerver.com/package/?id=EPiServer.Labs.BlockEnhancements&v=0.7.1
