### ISSUE TITLE
Problem adding EPiServer Forms elements with Inline Block Editing

### ISSUE THREAD

**Issue by Nucleuz** [episerver/EPiServer.Labs.BlockEnhancements#42]
Hi,

I have a problem adding new EPiServer Form elements using Inline Block Editing.

![gif_forms_inline_add_element](https://user-images.githubusercontent.com/7115091/72902327-902d5700-3d2b-11ea-8a94-eeeb50b5200b.gif)

I've attached a gif showing the problem.
The problem is that I cannot add elements to a EPiServer Form if I use Inline Editing on the form. Adding an element show the "New form element" page behind the Inline Editing window.

Is this a bug or do you not support this feature?

**Comment by barteksekula** [comment]
@Nucleuz I'm moving this issue to https://github.com/advanced-cms/forms which is a package that brings both this Labs with Forms addon
will look into it soon
