### ISSUE TITLE
Inline edit is greyed out in menu

### ISSUE THREAD

**Issue by kristinkelley** [episerver/EPiServer.Labs.BlockEnhancements#45]
For this specific way of using inline block editing, the "inline block edit" is greyed out even if it is accessible using double clicking. This seems inconsistent. See it reproduced in the clip below.

![inline-block-edit](https://user-images.githubusercontent.com/19471467/74066623-be7f8780-49f7-11ea-86b8-e893001a4d69.gif)

**Steps to reproduce:**
1. Edit a page that contains a block in a content area property
2. Open the content area block menu by clicking once on a block
3. Click the hamburger menu for the exact same block

**Expected result:**
Inline block edit is clickable

**Actual result:**
Inline block edit is greyed out

**Additional information:**

- For example. If the 4th block in the content area is clicked to open the block menu, then the "inline block edit" is greyed out in hamburger menu for the 4th block only. This happens only if the 4th block's hamburger menu is the first one clicked after opening the block menu. Opening the hamburger menu for any other block in the content area will result in the "inline block edit" not being greyed out for the 4th block anymore.

- Closing the hamburger menu and then opening it again (on the same block) does not make "inline block edit" clickable.

- After closing the hamburger menu, then opening it on **_another_** block, then opening it again on the first block makes "inline block edit" clickable again.

- Double clicking always works.

**Comment by barteksekula** [comment]
Fixed in https://github.com/episerver/EPiServer.Labs.BlockEnhancements/commit/2ee397b7a67139b886cc8762ec8ba30ed1db4ab3

Will be released in 0.7.2
