### ISSUE TITLE
Feature request: Inline block edit - Translate

### ISSUE THREAD

**Issue by markprins81** [episerver/EPiServer.Labs.BlockEnhancements#47]
When you drag a block in a different language on a page it displays a warning icon, and text explaining this block does not exist in the page language and it will not be visible because of that.

The content editor now has to navigate to the normal block edit, where they can click 'translate' to create another language version of the block.

Would it be possible to add the translate button to the inline edit so that content editors can translate the block from inline edit view?

**Comment by barteksekula** [comment]
Released in https://world.episerver.com/blogs/bartosz-sekula/dates/2020/4/translate-content-items-without-switching-context/
https://nuget.episerver.com/package/?id=EPiServer.Labs.BlockEnhancements&v=0.8.0
