### ISSUE TITLE
javascript errors after updating from 0.6.3 to 0.7

### ISSUE THREAD

**Issue by mhwlng** [episerver/EPiServer.Labs.BlockEnhancements#48]
CMS stopped working with javascript errors after updating nuget package from 0.6.3 to 0.7 :

![Annotation 2020-02-25 081753](https://user-images.githubusercontent.com/1388886/75224278-7f4b8780-57a8-11ea-9d64-45a9d504f17f.jpg)

(note that we are using on-premise episerver, so don't have Azure Application Insights)

**Comment by nicklasisraelsson** [comment]
Thanks @mhwlng we'll look at it right away.

**Comment by nicklasisraelsson** [comment]
We've removed the faulty 0.7.0 package from the public feed and created a new 0.7.1 package that contains the missing file (tracker.js). If you are affected by this error you need to update.
