### ISSUE TITLE
Unable to add dependency on form elements using inline edit

### ISSUE THREAD

**Issue by inefoss** [episerver/EPiServer.Labs.BlockEnhancements#49]
Hi, 

The list of form elements to add a dependency on is empty when using the inline edit. It is working when editing the element the normal way. See the video underneath for example:

![inline-edit-dependencies](https://user-images.githubusercontent.com/37294947/75686322-5e010480-5c9c-11ea-83de-169f972f1701.gif)

**Steps to reproduce:** 
1. Double click a form element 
2. Scroll down to Dependencies 
3. Click "+" to add condition

**Expected result:** 
See list of form elements to add dependency on

**Actual result:**
List is empty

**Comment by barteksekula** [comment]
Moving that issue to https://github.com/advanced-cms/forms/issues/3
It is not possible to fix in episerver-labs-block-enhancements as we do not have a dependency on the forms package.
v0.2.0 will soon be released for https://nuget.episerver.com/package/?id=Advanced.CMS.Forms
