### ISSUE TITLE
"Publish content with local blocks" can't publish local block version in non-master language

### ISSUE THREAD

**Issue by gregwiechec** [episerver/EPiServer.Labs.BlockEnhancements#5]
**Steps to reproduce**:
1. Block1 is a local block for Page1
2. Page1 has 2 language versions: Page1_en (published) and Page1_sv (published)
3. Block1 has 2 language versions: Block1_en (unpublished) and Block1_sv (unpublished)
4. Open Page1_sv
5. Click Publish > "Publish content with local blocks" menu.
**Expected**: Block1_sv is published.
**Actual**: Block1_sv isn't published.

**Comment by barteksekula** [comment]
Not an issue any more, after changing the data source for the Smart Publish command (no longer getting contextual folder's children but rather actual items that are in use.
