### ISSUE TITLE
Cannot see the whole Richtext editor

### ISSUE THREAD

**Issue by Nucleuz** [episerver/EPiServer.Labs.BlockEnhancements#50]
Hi,
 
The problem is that you cannot see the whole editor when you decrease the width of your browser. The editor is not responsive.
The width is set to 1000 and height to 300 in our TinyMce configuration.

![richtext-cutoff](https://user-images.githubusercontent.com/7115091/76748233-af1ff680-677a-11ea-86eb-ade12303c7b0.PNG)

![gif_tinymce_12mar](https://user-images.githubusercontent.com/7115091/76748248-b810c800-677a-11ea-9a12-21563f07cd75.gif)

I reported the problem to EPiServer support, but they encouraged me to report the problem here:
_Our Dev team is aware of the bug. But I'm sorry to say that, we only have limited support to Lab.BlockEnhancement. Since the bug is not major, we won't fix it for now. And we also encourage you to report bug in github, so that community can contribute._

I've previously reported the same problem to EPiServer Support regarding EPiServer Forms, and they fixed the problem by adding a horizontal scroll bar.

Would it be possible to fix this?

**Comment by barteksekula** [comment]
@Nucleuz Thanks for reporting this. I checked and it's actually an issue in the core package.
![image](https://user-images.githubusercontent.com/1321664/76848823-a09e1180-6844-11ea-9055-66911abc1ccf.png)
As you can see the same thing happens with the default Forms view, no scrollbar is shown if the form does not fit into the area.
I will consult with the team tomorrow morning and let you know, hopefully we can fix it in the CMS.UI package.

**Comment by nicklasisraelsson** [comment]
This will be looked at and addressed by the CMS product. 

This is the public bug for it: https://world.episerver.com/support/Bug-list/bug/CMS-15549

**Comment by Nucleuz** [comment]
Hi Nicklas,

I checked to see if the bug had been fixed: [https://world.episerver.com/support/Bug-list/bug/CMS-15549](https://world.episerver.com/support/Bug-list/bug/CMS-15549)

It just says "Closed, Won't fix". I cannot find any reason for why it won't be fixed. Do you have any idea what I can do next? The issue has not been fixed

**Comment by nicklasisraelsson** [comment]
Since the size is set by javascript in the core product fixing it in CMS UI would have too many side effects. We will instead do a specific solution for the Block enhancements. Reopening this issue.

**Comment by Nucleuz** [comment]
Hi bartekekula,
I tried updating to version 0.8.1 (latest stable) via Nuget Package Manager, but it fails to update since it cannot find the EPiServer.Telemetry.UI dependency:
![image](https://user-images.githubusercontent.com/7115091/81811379-d7cb2f00-9524-11ea-8a3e-55cdb853ba27.png)

I cannot seem to figure out what I am doing wrong. Is EPiServer.Telemetry.UI not in the EPiServer package feed ?

**Comment by barteksekula** [comment]
@Nucleuz sorry, that's my bad. one of 0.8.1 dependencies was not made public yet, so 0.8.1 should not have been published yet (it will be by the end of the month) but for now we had to remove it from the public feed.

However in the meantime we had another general fix in the CMS product which is tracked by 
https://world.episerver.com/support/Bug-list/bug/CMS-15823
It will be released in EPiServer.CMS.UI 11.25.0 soon, at the moment the fix is being verified by the QA

**Comment by barteksekula** [comment]
Please install https://nuget.episerver.com/package/?id=EPiServer.CMS.UI&v=11.25.0

**Comment by barteksekula** [comment]
It would be helpful if you could confirm that 11.25.0 solves your problem. THanks

**Comment by barteksekula** [comment]
It's also available here: https://nuget.episerver.com/package/?id=EPiServer.Labs.BlockEnhancements&v=0.8.1
