### ISSUE TITLE
Can not create/edit inline block that use custom ClientEditor

### ISSUE THREAD

**Issue by tanvu-epi** [episerver/EPiServer.Labs.BlockEnhancements#53]
I have a custom ClientEditor (rgba color picker using Vanilla picker plugin).
But I can not Create/Edit the block that use this ClientEditor from page's ContentArea.
[Video demo](https://vimeo.com/405727967)

`[ClientEditor(ClientEditingClass = "foundation/editors/ColorPicker")]`
`public virtual string OverlayTextColor { get; set; }`

This's my js file (text format because Github does not allow include js file)
[ColorPicker.txt](https://github.com/episerver/EPiServer.Labs.BlockEnhancements/files/4480763/ColorPicker.txt)

**Comment by barteksekula** [comment]
@tanvu-epi any errors in the console?

**Comment by tanvu-epi** [comment]
> @tanvu-epi any errors in the console?

No, you can see in this video
https://vimeo.com/408227259

**Comment by barteksekula** [comment]
does it work if you comment out the ClientEditor attribute from OverlayTextColor ?

**Comment by tanvu-epi** [comment]
> does it work if you comment out the ClientEditor attribute from OverlayTextColor ?

Yes, it not work with any block use that custom ClientEditor, but only get error in Inline Edit/Create (not sure that's what error because console log doesn't show any bug).

**Comment by barteksekula** [comment]
ok, thanks for info, we will triage this soon
