### ISSUE TITLE
Menu item for "edit" on block is changed to "view"

### ISSUE THREAD

**Issue by Drol** [episerver/EPiServer.Labs.BlockEnhancements#54]
Why does BlockEnhancements change the menu item to edit (not inline) a block from "edit" to "view" and the icon is a search icon which is confusing.

Also the translation resource for "view" is pulled from epi/i18n!epi/cms/nls/episerver.shared.action so it is impossible for us to change the text in lang file. At least not without changing the translation in other places too.

At least make it possible to change in lang file  :-)

**Comment by barteksekula** [comment]
We did it because we introduced the Inline Edit action and it felt more naturlal to change the old 'Edit' to 'View' since in fact it just redirects the user to the given contentLink while the new Inline Edit pops up a dialog with form.
Let us see what we can do.

**Comment by Drol** [comment]
OK I see. Out customers editors got confused. Basically they didn't understand they could get to the normal edit page where they can do DnD blocks etc.

I think actually what they would want is to have is double click == normal edit and just the extra option to do a inline edit to do quick fixes.

**Comment by nicklasisraelsson** [comment]
We're going to revert the name change so that is says "Edit". Contributions are welcome.

**Comment by barteksekula** [comment]
Will be published next week in https://nuget.episerver.com/package/?id=EPiServer.Labs.BlockEnhancements&v=0.8.3
