### ISSUE TITLE
Blocking overlay when using the "inline create" functionality

### ISSUE THREAD

**Issue by SamDenHaerynck** [episerver/EPiServer.Labs.BlockEnhancements#63]
Hi, 

When you create a new block using the inline create feature, a pop-up opens with the properties to configure. 
In the scenario where you have for example an image block which has a required content area where you can drop image slide blocks (see screenshot), you are completely stuck. 

You cannot save, because the required field is not filled. 
You cannot drag and drop blocks from the blocks folder because of the overlay. 
You don't have some sort of picker (as you have for assets) to select an existing block.  

![image](https://user-images.githubusercontent.com/8938557/92710685-4c3d9f80-f358-11ea-8a61-c75017de56ff.png)

Please provide a suitable solution that we can enable this feature for all our running Episerver projects. 

Kind regards,
Sam Den Haerynck
delaware

**Comment by tednyberg** [comment]
This has been on my wish list since April, through #52.

I really hope this makes it into a future release to avoid us having to "hack" the add-on dialog to disable the overlay. 🙏

**Comment by barteksekula** [comment]
@tednyberg it's now part of CMS UI https://nuget.episerver.com/package/?id=EPiServer.CMS.UI&v=11.34.0
The Quick Edit dialog no longer blocks the page tree or assets pane.
