### ISSUE TITLE
Preview unpublished blocks in XHTML-property

### ISSUE THREAD

**Issue by jtonvang** [episerver/EPiServer.Labs.BlockEnhancements#66]
Using draft-mode, the ContentArea-property renders unpublished changes in blocks, which is great - however, this does not work for blocks that the editor has added in an XHTML-property, which creates an inconsistent experience for the editors.

**Comment by barteksekula** [comment]
Block enahancements are going to be obsoleted. Most of its functionality is being moved to CMS UI package. A new compatibility release will be released soon, compatible with 12.18.0
