### ISSUE TITLE
0.10.0/Scripts/inline-editing/commands/inline-edit.js net::ERR_ABORTED 404 (Not Found)

### ISSUE THREAD

**Issue by SujitSenapati** [episerver/EPiServer.Labs.BlockEnhancements#68]
With latest version of the module we are having issue with loading inline-edit and it prevents loading the CMS properties & preview of the pages.

See the error from console. 
episerver-labs-block-enhancements/0.10.0/Scripts/inline-editing/commands/inline-edit.js net::ERR_ABORTED 404 (Not Found)

See screenshot
![Capture](https://user-images.githubusercontent.com/13890307/107683212-eb97f300-6c66-11eb-8c7e-ed9dbeca1c87.PNG)

Regards
Sujit

**Comment by LingSpb** [comment]
inline-edit.js was removed from 0.10.0. Could you check if you use that file somewhere in your code? If it's the case, "epi-cms/contentediting/command/BlockInlineEdit" (which is available from CMS UI 11.32.0) should be used instead.

**Comment by pontushagman** [comment]
I get the same error.

**Comment by barteksekula** [comment]
it's because of https://github.com/advanced-cms/forms - it's not compatible yet as it's still referencing the old file https://github.com/advanced-cms/forms/blob/master/src/Alloy.Sample/modules/_protected/advanced-cms-forms/1.0.0/Scripts/initializer.js#L5

**Comment by barteksekula** [comment]
@pontushagman @SujitSenapati Please just uninstall https://nuget.episerver.com/package/?id=Advanced.CMS.Forms
It's no longer needed as we moved its functionality to CMS UI.

**Comment by pontushagman** [comment]
Yay! Long-awaited.
