### ISSUE TITLE
Some issues found with BH

### ISSUE THREAD

**Issue by jwengelin** [episerver/EPiServer.Labs.BlockEnhancements#69]
Hello! Alot of the functions in BH are great and one of our clients wanted to implement it. However due to some issues with it we had to pull it which is a shame. I will list some of the issues we found.

1. Inline edit pop up and its size is inconsistent. We had reports of users opening the popup and the all of the content was not shown inside. Then the user closed the inline edit and it worked better, showing all of the content. Maybe some ability to resize the inline edit modal?
2. Draft mode is not working properly for all blocks, not sure what is causing this. Also blocks within blocks i believe it does not work with, though perhaps this is not intended.
3. When using a block with an image property, drag and drop does not work with the inline edit mode.

**Comment by barteksekula** [comment]
Hi Joel,

1. Could you please provide more details? Was the dialog not scrollable?
2. Which blocks are not working? Are those blocks part of content area or not?
3. This is addressed in EPiServer.CMS.UI 11.34.0 that will be released any time soon. The assets pane is no longer blocked when opening Inline Edit dialog.

**Comment by jwengelin** [comment]
I believe the first issue occured when trying to inline edit a text editor block. Issue was that you had to scroll sideways to view all of the text, however after closing and using the inline edit again the dialog window was more adjusted to the content inside. I have asked for more details on the this issue and i will try to return with some images to show the issue.

Second issue was a script block meant for code or html and it did not properly show if it was a draft or not. I will check wether it was part of a contentarea or not.

**Comment by jwengelin** [comment]
Here is an image of the block problem. The image below is a script block which should be in draft mode but is not.
![exampleblockdraft](https://user-images.githubusercontent.com/54437463/110341550-bc3c9200-802a-11eb-9ce4-60b6d9bb1866.png)

**Comment by barteksekula** [comment]
Can you please paste the views code?
Of the main block and the nested block.

**Comment by barteksekula** [comment]
Please try to use the official CMS UI and the new Quick Edit command from https://nuget.episerver.com/package/?id=EPiServer.CMS.UI&v=11.34.0
That should solve point1
