### ISSUE TITLE
We need a way to handle concurrently inline editing

### ISSUE THREAD

**Issue by gregwiechec** [episerver/EPiServer.Labs.BlockEnhancements#7]
**Steps to reproduce**:

PageC has BlockD added to a property such as content area.
UserA and UserB login the system and edit a PageC
UserA and UserB inline edits BlockD concurrently.
UserA changes sth in BlockD and save
UserB changes sth in BlockD and save
=> There are 2 draft versions created. Draft version created by User A is primary.
UserB opens context menu vs. BlockD, he doesn't see "Publish Changes" until he refreshes whole page.
UserB inline publishes BlockD and inline edit it again
Expected result:
We should inform user about concurrently inline editing like the way we do with normal editing content.

**Actual result**:
Changes created by UserA are published and shown to user. (Primary draft version is published)
I think UserB maybe confused because his changes to BlockD aren't published because he doesn't know someone else saves his change earlier.

**Comment by barteksekula** [comment]
won't fix
