### ISSUE TITLE
Not able to add name when creating new blocks after upgrade

### ISSUE THREAD

**Issue by zbrilhart** [episerver/EPiServer.Labs.BlockEnhancements#78]
Prerequisite: EPiServer.CMS.UI 11.35.3 and EPiServer.Labs.BlockEnhancements 0.10.0. 

After upgrading EPiServer.CMS.UI to 11.35.3, the modal window for creating a new block in a content area does not show a field for the Name property. It works fine when a block is created in the assets pane. 

With block enhancements uninstalled the issue does not occur. 

Steps to reproduce:

- Locate a content area property on the properties of a page in the CMS UI. 
- Within the content area property click "create a new block"

Expected: a place to add the name property
Actual: the name property is not present on this modal window. It is also not on the next block properties modal window. 

![1](https://user-images.githubusercontent.com/12052855/131026836-23f334c9-75be-44a0-bca6-1e03a766fc10.png)
![2](https://user-images.githubusercontent.com/12052855/131026835-f1c18d36-33af-4c48-af4b-666429550b74.png)
![3](https://user-images.githubusercontent.com/12052855/131026832-49c5fbb7-6153-4b9f-a340-45971d7a2b7a.png)

**Comment by LingSpb** [comment]
We moved some features from Labs.BlockEnhancements to our product with some changes, which was release in EPiServer.CMS.UI 11.32.0.
By default, in Quick Edit, the Name property is set to be hidden, blocks created from an inline edit dialog will get an automatically generated name with the default format is [**PageName BlockType AutoIncrementId**].

You can override the default auto-generated name by implementing ILocalAssetNameGenerator.

You can enable the Name property by setting ShowNameProperty to true.

Here is the guideline for working with inline edit blocks https://world.optimizely.com/documentation/developer-guides/CMS/Content/inline-edit-settings/
