### ISSUE TITLE
"Publish content with local blocks" is hidden in non-master language

### ISSUE THREAD

**Issue by gregwiechec** [episerver/EPiServer.Labs.BlockEnhancements#8]
**Steps to reproduce**:
1. Block1 is a local block for Page1
2. Page1 has 2 language versions: Page1_en (published) and Page1_sv (published)
3. Block1 has 2 language versions: Block1_en (published) and Block1_sv (unpublished)
4. Open Page1_sv
5. Click Options drop-down button
**Expected**: "Publish content with local blocks" menu is enabled
**Actual**: "Publish content with local blocks" menu is hidden

**Comment by barteksekula** [comment]
We always show the new command now, it's called "Smart Publish".
