### ISSUE TITLE
On page editing does not update if page/block is pending publish

### ISSUE THREAD

**Issue by hallatore** [episerver/EPiServer.Labs.BlockEnhancements#82]
When editing a contentArea with blocks, where the page/block is already pending a publish (Publish button is available), the on page preview of the block is not updated.

**Steps to reproduce**

1. Use the on page edit
2. Add a block to a content area
3. See that the "Changed to be published" status is showing
4. Note: If you edit the block again now the changes will be rendered correctly.
4. Refresh the page (Ctrl + R)
5. Edit the block again
6. Notice that the block changes are not rendered on the page

**Comment by hallatore** [comment]
I found that it works if i go into the given version of the content. aka 123456_654321 instead of just 123456. But epi only uses the main id as long as your not viewing a specific version.

Works: /EPiServer/CMS/?language=en#context=epi.cms.contentdata:///82310_865253
Doesn't work: /EPiServer/CMS/?language=en#context=epi.cms.contentdata:///82310

**Comment by barteksekula** [comment]
Fixed in https://nuget.optimizely.com/package/?id=EPiServer.Labs.BlockEnhancements&v=1.0.1

**Comment by hallatore** [comment]
@barteksekula It's fixed in a version we can never adopt, since the project is stuck on net-framework 😭

**Comment by barteksekula** [comment]
Hmm, actually it does not work in 1.0.1 either. I will try to apply a proper fix in both .net core and .net framework.

**Comment by evdinursan** [comment]
Hi! Can you please tell me if you have any date set for the release of 0.12.1? Thank you for your time!

**Comment by barteksekula** [comment]
I've just checked and the package has already gone through our QA process and it's already waiting in the release queue which means it should be public around tuesday next week.

**Comment by barteksekula** [comment]
https://nuget.optimizely.com/package/?id=EPiServer.Labs.BlockEnhancements&v=0.12.1 is out
this bugfix will also be available in 1.0.2 which will be out soon
