### ISSUE TITLE
"Edit" are showing twice when click on the context menu of the blocks within for this page only

### ISSUE THREAD

**Issue by vyan024** [episerver/EPiServer.Labs.BlockEnhancements#85]
## Steps to reproduce
1. Turn off "HideForThisFolder"
2. Click on context menu next to the block under "for this page only", there are two "Edit" showing in the context menu, one is the original edit option, the second seems the quick edit option

![image](https://user-images.githubusercontent.com/54790930/148722703-8cfdb2bf-5c9c-417f-b29e-c45105dbd307.png)

**Comment by LingSpb** [comment]
Fixed in 0.12.0
