### ISSUE TITLE
Adding image for this page does not come through in content loader

### ISSUE THREAD

**Issue by damiendias** [episerver/EPiServer.Labs.BlockEnhancements#86]
When uploading an image direct from file explorer to a page it gets stored as a local asset for this page and inherits the publishing cycle of the page which is fine. So when the page is published the image does come through except any associated meta data of the image for example (Alt Text, Caption, etc.) is all null even though it has been published.

This applies to version 1.0.0 for CMS 12.

**Comment by barteksekula** [comment]
@damiendias 
1. When do you edit the metadata of the uploaded image?
2. Do you have `Publish image on upload` option turned on?

**Comment by damiendias** [comment]
Hi @barteksekula 

For question 1 the meta data is updated after the image has been uploaded direct from the windows browser. We then navigate across to the assets pane in the "For this Page" area and edit the meta data of the asset from there. That is where we don't have the option to publish it as it is a part of the parent page. But when we publish the page nothing still comes through.

For question 2 I am assuming this is the case. I actually can't find this option in the CMS 12 Admin area anymore.

**Comment by barteksekula** [comment]
Block enahancements are going to be obsoleted. Most of its functionality is being moved to CMS UI package. A new compatibility release will be released soon, compatible with 12.18.0
