### ISSUE TITLE
Quick edit not ignored on page specific blocks

### ISSUE THREAD

**Issue by adayinthelifeofapro** [episerver/EPiServer.Labs.BlockEnhancements#89]
If you are trying to disable the block enhancements quick edit option on specific blocks, if you specify ignore in the way highlighed in the red box, the quick edit is disabled for global blocks but not page specific blocks, instead if you specify ignore in the way highlighted in green quick edit is disabled for both global and page specific

![image](https://user-images.githubusercontent.com/108930057/208447350-bfb189c8-32bc-4176-9c48-6c31a6f305c3.png)

**Comment by barteksekula** [comment]
Block enahancements are going to be obsoleted. Most of its functionality is being moved to CMS UI package. A new compatibility release will be released soon, compatible with 12.18.0
