### ISSUE TITLE
Block Enhancements don't work correctly with Optimizely CMS 12

### ISSUE THREAD

**Issue by solita-kpetrov** [episerver/EPiServer.Labs.BlockEnhancements#90]
We have tried to install the package for Optimizely CMS 12 and faced compatibility issues, for example:
- the package breaks Edit/Quick Edit functionality that is already implemented for 12 version by default. The package supports only Edit or only QuickEdit but not both simultaneously. 
- publish Pages and Blocks functionality seems doesn't work

We'd like to use some other features from this package, but it's not possible with 12 version without loosing some default functionality.

**Comment by ynzenu** [comment]
I had the same problems/confusion while installing it for CMS version 12.17
- Edit/Quick Edit — This is a default feature that will hide the options based on if the block is local or shared. You can change this by configuring the features as described [here](https://github.com/episerver/EPiServer.Labs.BlockEnhancements#configuring-enabled-features). Set `LocalContentFeatureEnabled` to `false`, or `AllowQuickEditOnSharedBlocks` to `true`.
- Same thing here, the "publish Pages and Blocks" feature is turned off by default. Set `PublishPageWithBlocks` to `true` in the startup configuration.

I suggest reviewing all configurable options [here](https://github.com/episerver/EPiServer.Labs.BlockEnhancements#blockenhancementsoptions).

**Comment by barteksekula** [comment]
Block enahancements are going to be obsoleted. Most of its functionality is being moved to CMS UI package. A new compatibility release will be released soon, compatible with 12.18.0
